In [1]:
import sys
import mysql.connector

import pandas as pd
import sys
import mysql.connector
import numpy as np
import os
from dotenv import load_dotenv
load_dotenv()
#ESTE ARGUMENTO NO SE USA EN ESTE REPORTE, SER√Å 0 SIEMPRE UWU
id=0
#configurar la conexion a la base de datos
DB_USERNAME = os.getenv('DB_USERNAME')
DB_DATABASE = os.getenv('DB_DATABASE')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_PORT = os.getenv('DB_PORT')
# Conectar a DB
cnx = mysql.connector.connect(user=DB_USERNAME,
                              password=DB_PASSWORD,
                              host='localhost',
                              port=DB_PORT,
                              database=DB_DATABASE,
                              use_pure=False)

In [7]:
#Tablas paneles
tablas = ['two_in_joist_l_galvanized_panels','two_in_joist_l_painted_panels','two_point_five_in_joist_l_galvanized_panels','two_point_five_in_joist_l_painted_panels','chair_joist_galvanized_panels','chair_joist_l_painted_panels']

In [8]:
for i in tablas:
    print(i)
    cnx.cursor().execute('alter table '+i+' add column loading_capacity float')

chair_joist_l_painted_panels

In [11]:
l2=pd.read_excel('l2.xlsx',sheet_name=None)

In [14]:
dict={0.05,0.1,0.15,0.2,0.35,0.3}

,Unnamed: 0,"PANELES METALICOS CALIBRE 24 PARA VIGA ""L"" DE 2 IN DE PATIN",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,DESARROLLO,NaN,DIMENSIONES VENTA,NaN,NaN,CAPACIDAD DE CARGA EN KG,SKU,CALIBRE,KG / M2,PESO,M2,PRECIO VENTA
1,NaN,FONDO M,FRENTE M,ANCHO (M),LARGO M,P/ MARCO FDO,NaN,NaN,NaN,NaN,NaN,NaN,PINTADO
2,NaN,0.15,0.935,0.05,0.863,0.91,30,TC0000116704,24,4.44,0.62,0.28,101.47
3,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116705,24,4.44,0.72,0.33,117.75
4,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116706,24,4.44,0.81,0.36,131.86
5,NaN,0.2,0.935,0.1,0.863,0.91,30,TC0000116707,24,4.44,0.83,0.37,135.29
6,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116708,24,4.44,0.96,0.43,157.00
7,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116709,24,4.44,1.08,0.49,175.81
8,NaN,0.24,0.935,0.15,0.863,0.91,40,TC0000116710,24,4.44,1.00,0.45,162.35
9,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116711,24,4.44,1.16,0.52,188.40
10,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116712,24,4.44,1.29,0.58,210.97
11,NaN,0.3,0.935,0.2,0.863,0.91,40,TC0000116713,24,4.44,1.25,0.56,202.94
12,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116714,24,4.44,1.45,0.65,235.49
13,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116715,24,4.44,1.62,0.73,263.71
14,NaN,0.35,0.935,0.25,0.863,0.91,40,TC0000116716,24,4.44,1.45,0.65,236.76
15,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116717,24,4.44,1.69,0.76,274.74
16,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116718,24,4.44,1.89,0.85,307.66
17,NaN,0.4,0.935,0.3,0.863,0.91,40,TC0000116719,24,4.44,1.66,0.75,270.58
18,NaN,NaN,1.085,NaN,1.013,1.06,NaN,TC0000116720,24,4.44,1.93,0.87,313.99
19,NaN,NaN,1.215,NaN,1.143,1.2,NaN,TC0000116721,24,4.44,2.16,0.97,351.61

In [16]:
tablas[0]

'two_in_joist_l_galvanized_panels'

In [25]:
#Rellenando por calibre cada tabla, esto lo hago viendo los exceles
#y cambiando el indice de tablas[]
calibre=14
low=170
high=200
cnx.cursor().execute('update '+tablas[0]+' set loading_capacity = '+str(low)+' where background_dimension <= 0.1 and caliber='+str(calibre))
cnx.cursor().execute('update '+tablas[0]+' set loading_capacity = '+str(high)+' where background_dimension > 0.1 and caliber='+str(calibre))
cnx.commit()